
spring:
  ###### ACTIVE PROFILE ######
  profiles:
    active: local
  # view setting
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # Redis
  redis:
    host: localhost
    port: 6379

  #devtools
  devtools:
    livereload:
      enabled: true

# tomcat setting
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


# mybatis
mybatis:
  type-aliases-package: com.example.pof.model


# --- Amazon DynamoDB 
amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accesskey:
    secretkey:

      # query logging
      #logging:
      #  level:
      #    root: WARN
      #    org:
      #      springframework: DEBUG
      #    com:
      #      lotte:
      #        dev:
      #          demo:
      #            root: DEBUG
      #            controller: DEBUG
      #            repository: TRACE

    # datasources

datasource:
  dev:
    jdbc-url: jdbc:mysql://localhost:3306/FOO
    username: root
    password: password
    validation-query: 'SELECT 1'
    maxTotal: 100
    maxIdle: 30
    maxWaitMillis: 10000
    initialize: true


rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672" #JMS Port
    - "15672:15672" #Management Port - default guest:guest

    